### ISSUE TITLE
LUA-Aandroid 测试结果

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-inmobi-sample#5]
### inmobi 版本：1.5.1.2（sdkbox update --staging）

初始顶部只有hello lua 字样， 等待一会出现广告条（但是点击这个广告条应用就会崩溃）

**Comment by tinybearc** [comment]
点击： clickme
结果：弹出全屏inmobi的广告页面。 有时候会点击无反应，输出结果为：
[LUA-print] Entry invokeFun
[LUA-print] inmobi interstitial ad is not ready

**Comment by hugohuang1111** [comment]
同#2
